import { Badge } from "@/components/ui/badge";

export const mockOrderData = [
  {
    groupName: "สายการผลิต A (Production Line A)",
    groupCode: "LINE-A",
    orders: [
      {
        id: "EQM-1001",
        supplier: "J-2568-001 / ตรวจสอบระบบไฮดรอลิก (PM)",
        orderbookId: "WO-2568-11-001",
        orderDate: "15/11/2568",
        vendorCode: "HYD-OIL-32",
        vendorName: "น้ำมันไฮดรอลิก PTT H-32 (ถัง 200 ลิตร)",
        unit: "1",
        packSize: "ถัง",
        deliveryDate: "16/11/2568",
        status: "อนุมัติ",
        details: {
          requester: "นายสมชาย ใจดี (ฝ่ายผลิต)",
          requestDate: "15/11/2568 10:30:00",
          approver: "นายวิศิษฐ์ ช่างซ่อม",
          approveDate: "15/11/2568 09:00:15",
          lastEditor: "นายวิศิษฐ์ ช่างซ่อม",
          lastEditDate: "15/11/2568 09:00:15",
          department: "ซ่อมบำรุง (Maintenance)",
          contact: "ทีมซ่อมบำรุง 1",
          vendorInvoice: "REF-MAINT-A01",
          rejectionReason: null,
        },
        items: [
          {
            "#": 1,
            itemCode: "HYD-OIL-32",
            itemName: "น้ำมันไฮดรอลิก PTT H-32 (ถัง 200 ลิตร)",
            vendorItemCode: "PTT-H32-200L",
            itemNameVendor: "น้ำมันไฮดรอลิก PTT เบอร์ 32 (200L)",
            itemNameDetail: "น้ำมันไฮดรอลิก PTT H-32 บรรจุถัง 200 ลิตร",
            qty: "0.5",
            unit: "ถัง",
            packSize: "200",
            unitPkg: "ลิตร",
            returnDate: null,
          },
        ],
      },
      {
        id: "EQM-1002",
        supplier: "J-2568-002 / ซ่อมมอเตอร์ขับเคลื่อน (CM)",
        orderbookId: "WO-2568-11-002",
        orderDate: "16/11/2568",
        vendorCode: "MIXED",
        vendorName: "รายการอะไหล่รวม",
        unit: "2",
        packSize: "รายการ",
        deliveryDate: "16/11/2568",
        status: "รออนุมัติ",
        details: {
          requester: "กะกลางคืน (ฝ่ายผลิต)",
          requestDate: "16/11/2568 03:00:00",
          approver: "-",
          approveDate: "-",
          lastEditor: "นายสมชาย ใจดี",
          lastEditDate: "16/11/2568 08:00:00",
          department: "ซ่อมบำรุง (Maintenance)",
          contact: "ทีมซ่อมบำรุง 2",
          vendorInvoice: "REF-MAINT-A02",
          rejectionReason: null,
        },
        items: [
          {
            "#": 1,
            itemCode: "BEARING-6205",
            itemName: "ตลับลูกปืน 6205-2Z",
            vendorItemCode: "SKF-6205-2Z",
            itemNameVendor: "SKF Bearing 6205-2Z",
            itemNameDetail: "ตลับลูกปืนเม็ดกลมร่องลึก ฝาเหล็ก 2 ข้าง",
            qty: "2",
            unit: "ชิ้น",
            packSize: "1",
            unitPkg: "ชิ้น",
            returnDate: null,
          },
          {
            "#": 2,
            itemCode: "DRILL-MAK-01",
            itemName: "สว่านไฟฟ้า Makita M6001",
            vendorItemCode: "MAK-M6001",
            itemNameVendor: "สว่านไฟฟ้า Makita M6001",
            itemNameDetail: "สว่านไฟฟ้า 10mm",
            qty: "1",
            unit: "เครื่อง",
            packSize: "1",
            unitPkg: "เครื่อง",
            returnDate: "2025-11-20",
          },
        ],
      },
      {
        id: "EQM-1007",
        supplier: "J-2568-007 / ขอสำรองตลับลูกปืน (Stock)",
        orderbookId: "WO-2568-11-007",
        orderDate: "20/11/2568",
        vendorCode: "BEARING-6205",
        vendorName: "ตลับลูกปืน 6205-2Z",
        unit: "1",
        packSize: "ชิ้น",
        deliveryDate: "25/11/2568",
        status: "ไม่อนุมัติ",
        details: {
          requester: "นายสมชาย ใจดี",
          requestDate: "20/11/2568 10:00:00",
          approver: "นายวิศิษฐ์ ช่างซ่อม",
          approveDate: "20/11/2568 11:00:00",
          lastEditor: "นายวิศิษฐ์ ช่างซ่อม",
          lastEditDate: "20/11/2568 11:00:00",
          department: "ซ่อมบำรุง (Maintenance)",
          contact: "ทีมซ่อมบำรุง 2",
          vendorInvoice: "REF-MAINT-A05",
          rejectionReason: "เบิกเกินจำนวนที่กำหนด",
        },
        items: [
          {
            "#": 1,
            itemCode: "BEARING-6205",
            itemName: "ตลับลูกปืน 6205-2Z",
            vendorItemCode: "SKF-6205-2Z",
            itemNameVendor: "SKF Bearing 6205-2Z",
            itemNameDetail: "ตลับลูกปืนเม็ดกลมร่องลึก ฝาเหล็ก 2 ข้าง",
            qty: "200",
            unit: "ชิ้น",
            packSize: "1",
            unitPkg: "ชิ้น",
            returnDate: null,
          },
        ],
      },
      {
        id: "EQM-1004",
        supplier: "J-2568-004 / มอเตอร์สายพานเสียงดัง (BD)",
        orderbookId: "WO-2568-11-004",
        orderDate: "18/11/2568",
        vendorCode: "V-BELT-B50",
        vendorName: "สายพาน V-Belt B50",
        unit: "1",
        packSize: "เส้น",
        deliveryDate: "19/11/2568",
        status: "ยกเลิก",
        details: {
          requester: "นายสมชาย ใจดี (ฝ่ายผลิต)",
          requestDate: "18/11/2568 09:00:00",
          approver: "นายวิศิษฐ์ ช่างซ่อม",
          approveDate: "18/11/2568 10:00:00",
          lastEditor: "นายวิศิษฐ์ ช่างซ่อม",
          lastEditDate: "18/11/2568 11:00:00",
          department: "ซ่อมบำรุง (Maintenance)",
          contact: "ทีมซ่อมบำรุง 1",
          vendorInvoice: "REF-MAINT-A03",
          rejectionReason: "ผู้ขอเบิกแจ้งยกเลิกเอง",
        },
        items: [
          {
            "#": 1,
            itemCode: "V-BELT-B50",
            itemName: "สายพาน V-Belt B50",
            vendorItemCode: "MITSUBOSHI-B50",
            itemNameVendor: "สายพาน B50",
            itemNameDetail: "สายพานร่อง B เบอร์ 50",
            qty: "4",
            unit: "เส้น",
            packSize: "1",
            unitPkg: "เส้น",
            returnDate: null,
          },
        ],
      },
    ],
  },
];

export const initialStockData = [
  // 1.1 เครื่องมือทั่วไป (Hand Tools)
  {
    itemCode: "HAMMER-CLAW-01",
    itemName: "ค้อนหงอน ด้ามไฟเบอร์ 27mm",
    supplierName: "Stanley Tools",
    stock: 10,
    unit: "อัน",
    packSize: 1,
    unitPkg: "อัน",
    itemType: "Returnable",
    category: "เครื่องมือทั่วไป",
  },
  {
    itemCode: "HAMMER-SLEDGE-01",
    itemName: "ค้อนปอนด์ 5 LBS",
    supplierName: "Stanley Tools",
    stock: 5,
    unit: "อัน",
    packSize: 1,
    unitPkg: "อัน",
    itemType: "Returnable",
    category: "เครื่องมือทั่วไป",
  },
  {
    itemCode: "HEX-SET-MM-01",
    itemName: "ชุดประแจหกเหลี่ยม 9 ชิ้น (มิล)",
    supplierName: "King Tony",
    stock: 15,
    unit: "ชุด",
    packSize: 1,
    unitPkg: "ชุด",
    itemType: "Returnable",
    category: "เครื่องมือทั่วไป",
  },
  {
    itemCode: "WRENCH-ADJ-10IN",
    itemName: "ประแจเลื่อน 10 นิ้ว",
    supplierName: "King Tony",
    stock: 12,
    unit: "อัน",
    packSize: 1,
    unitPkg: "อัน",
    itemType: "Returnable",
    category: "เครื่องมือทั่วไป",
  },
  {
    itemCode: "WRENCH-SET-RING-01",
    itemName: "ประแจแหวน (ชุด 12 ชิ้น)",
    supplierName: "King Tony",
    stock: 8,
    unit: "ชุด",
    packSize: 1,
    unitPkg: "ชุด",
    itemType: "Returnable",
    category: "เครื่องมือทั่วไป",
  },
  {
    itemCode: "SOCKET-SET-1-2",
    itemName: "ชุดลูกบล็อก 1/2 นิ้ว (24 ชิ้น)",
    supplierName: "Koken",
    stock: 5,
    unit: "ชุด",
    packSize: 1,
    unitPkg: "ชุด",
    itemType: "Returnable",
    category: "เครื่องมือทั่วไป",
  },
  {
    itemCode: "PLIERS-LOCK-10IN",
    itemName: "คีมล็อก 10 นิ้ว",
    supplierName: "Yato",
    stock: 8,
    unit: "อัน",
    packSize: 1,
    unitPkg: "อัน",
    itemType: "Returnable",
    category: "เครื่องมือทั่วไป",
  },
  {
    itemCode: "PLIERS-COMBI-01",
    itemName: "คีมปากจิ้งจก 8 นิ้ว",
    supplierName: "Yato",
    stock: 10,
    unit: "อัน",
    packSize: 1,
    unitPkg: "อัน",
    itemType: "Returnable",
    category: "เครื่องมือทั่วไป",
  },
  {
    itemCode: "PLIERS-NEEDLE-01",
    itemName: "คีมปากแหลม 6 นิ้ว",
    supplierName: "Yato",
    stock: 10,
    unit: "อัน",
    packSize: 1,
    unitPkg: "อัน",
    itemType: "Returnable",
    category: "เครื่องมือทั่วไป",
  },
  {
    itemCode: "SCREWDR-SET-01",
    itemName: "ชุดไขควง (แฉก/แบน) 6 ชิ้น",
    supplierName: "Wera",
    stock: 10,
    unit: "ชุด",
    packSize: 1,
    unitPkg: "ชุด",
    itemType: "Returnable",
    category: "เครื่องมือทั่วไป",
  },
  {
    itemCode: "LADDER-A-6FT",
    itemName: "บันไดทรง A 6 ฟุต",
    supplierName: "Sankei",
    stock: 4,
    unit: "ตัว",
    packSize: 1,
    unitPkg: "ตัว",
    itemType: "Returnable",
    category: "เครื่องมือทั่วไป",
  },
  {
    itemCode: "TROLLEY-01",
    itemName: "รถเข็นของ 2 ล้อ",
    supplierName: "Local Supplier",
    stock: 3,
    unit: "คัน",
    packSize: 1,
    unitPkg: "คัน",
    itemType: "Returnable",
    category: "เครื่องมือทั่วไป",
  },

  // 1.2 เครื่องมือไฟฟ้า (Power Tools)
  {
    itemCode: "DRILL-MAK-01",
    itemName: "สว่านไฟฟ้า Makita M6001",
    supplierName: "Makita Thailand",
    stock: 5,
    unit: "เครื่อง",
    packSize: 1,
    unitPkg: "เครื่อง",
    itemType: "Returnable",
    category: "เครื่องมือไฟฟ้า",
  },
  {
    itemCode: "DRILL-CORDLESS-01",
    itemName: "สว่านไร้สาย Bosch GSB 18V",
    supplierName: "Bosch Thailand",
    stock: 3,
    unit: "ชุด",
    packSize: 1,
    unitPkg: "ชุด",
    itemType: "Returnable",
    category: "เครื่องมือไฟฟ้า",
  },
  {
    itemCode: "DRILL-ROTARY-01",
    itemName: "สว่านโรตารี่ 3 ระบบ Bosch",
    supplierName: "Bosch Thailand",
    stock: 3,
    unit: "เครื่อง",
    packSize: 1,
    unitPkg: "เครื่อง",
    itemType: "Returnable",
    category: "เครื่องมือไฟฟ้า",
  },
  {
    itemCode: "GRINDER-4IN-01",
    itemName: "เครื่องเจียร 4 นิ้ว (ลูกหมู) Makita",
    supplierName: "Makita Thailand",
    stock: 8,
    unit: "เครื่อง",
    packSize: 1,
    unitPkg: "เครื่อง",
    itemType: "Returnable",
    category: "เครื่องมือไฟฟ้า",
  },
  {
    itemCode: "JIGSAW-01",
    itemName: "เลื่อยจิ๊กซอ Bosch",
    supplierName: "Bosch Thailand",
    stock: 2,
    unit: "เครื่อง",
    packSize: 1,
    unitPkg: "เครื่อง",
    itemType: "Returnable",
    category: "เครื่องมือไฟฟ้า",
  },
  {
    itemCode: "CIRCULAR-SAW-7IN",
    itemName: "เลื่อยวงเดือน 7 นิ้ว",
    supplierName: "Makita Thailand",
    stock: 2,
    unit: "เครื่อง",
    packSize: 1,
    unitPkg: "เครื่อง",
    itemType: "Returnable",
    category: "เครื่องมือไฟฟ้า",
  },
  {
    itemCode: "HEATGUN-01",
    itemName: "เครื่องเป่าลมร้อน",
    supplierName: "Makita Thailand",
    stock: 3,
    unit: "เครื่อง",
    packSize: 1,
    unitPkg: "เครื่อง",
    itemType: "Returnable",
    category: "เครื่องมือไฟฟ้า",
  },
  {
    itemCode: "GLUEGUN-01",
    itemName: "ปืนยิงกาวไฟฟ้า",
    supplierName: "Stanley Tools",
    stock: 5,
    unit: "อัน",
    packSize: 1,
    unitPkg: "อัน",
    itemType: "Returnable",
    category: "เครื่องมือไฟฟ้า",
  },

  // 1.3 เครื่องมือวัด (Measuring Tools)
  {
    itemCode: "TAPE-MEASURE-5M",
    itemName: "ตลับเมตร 5 เมตร",
    supplierName: "Stanley Tools",
    stock: 20,
    unit: "อัน",
    packSize: 1,
    unitPkg: "อัน",
    itemType: "Returnable",
    category: "เครื่องมือวัด",
  },
  {
    itemCode: "VERNIER-6IN",
    itemName: "เวอร์เนียร์ คาลิปเปอร์ 6 นิ้ว",
    supplierName: "Mitutoyo",
    stock: 5,
    unit: "อัน",
    packSize: 1,
    unitPkg: "อัน",
    itemType: "Returnable",
    category: "เครื่องมือวัด",
  },
  {
    itemCode: "METER-DMM-01",
    itemName: "ดิจิตอล มัลติมิเตอร์",
    supplierName: "Fluke",
    stock: 5,
    unit: "เครื่อง",
    packSize: 1,
    unitPkg: "เครื่อง",
    itemType: "Returnable",
    category: "เครื่องมือวัด",
  },
  {
    itemCode: "METER-CLAMP-01",
    itemName: "แคลมป์มิเตอร์",
    supplierName: "Kyoritsu",
    stock: 3,
    unit: "เครื่อง",
    packSize: 1,
    unitPkg: "เครื่อง",
    itemType: "Returnable",
    category: "เครื่องมือวัด",
  },
  {
    itemCode: "LEVEL-WATER-12IN",
    itemName: "ระดับน้ำ 12 นิ้ว",
    supplierName: "Stanley Tools",
    stock: 8,
    unit: "อัน",
    packSize: 1,
    unitPkg: "อัน",
    itemType: "Returnable",
    category: "เครื่องมือวัด",
  },
  {
    itemCode: "LASER-DIST-01",
    itemName: "เลเซอร์วัดระยะ 50M",
    supplierName: "Bosch Thailand",
    stock: 2,
    unit: "เครื่อง",
    packSize: 1,
    unitPkg: "เครื่อง",
    itemType: "Returnable",
    category: "เครื่องมือวัด",
  },
  {
    itemCode: "THERMO-IR-01",
    itemName: "เทอร์โมมิเตอร์ อินฟราเรด",
    supplierName: "Fluke",
    stock: 3,
    unit: "เครื่อง",
    packSize: 1,
    unitPkg: "เครื่อง",
    itemType: "Returnable",
    category: "เครื่องมือวัด",
  },

  // 2. วัสดุ (เบิกเลย) - "Consumable"
  // 2.1 วัสดุสิ้นเปลือง (Fasteners & Supplies)
  {
    itemCode: "NAIL-2IN",
    itemName: "ตะปู 2 นิ้ว (กล่อง 1 กก.)",
    supplierName: "Thai Steel Fasteners",
    stock: 50,
    unit: "กล่อง",
    packSize: 1,
    unitPkg: "กล่อง",
    itemType: "Consumable",
    category: "วัสดุสิ้นเปลือง",
  },
  {
    itemCode: "NAIL-3IN",
    itemName: "ตะปู 3 นิ้ว (กล่อง 1 กก.)",
    supplierName: "Thai Steel Fasteners",
    stock: 50,
    unit: "กล่อง",
    packSize: 1,
    unitPkg: "กล่อง",
    itemType: "Consumable",
    category: "วัสดุสิ้นเปลือง",
  },
  {
    itemCode: "BOLT-M6-25MM",
    itemName: "น็อต M6x25mm (แพ็ค 100 ตัว)",
    supplierName: "Thai Steel Fasteners",
    stock: 20,
    unit: "แพ็ค",
    packSize: 100,
    unitPkg: "ตัว",
    itemType: "Consumable",
    category: "วัสดุสิ้นเปลือง",
  },
  {
    itemCode: "BOLT-M8-50MM",
    itemName: "น็อต M8x50mm (แพ็ค 100 ตัว)",
    supplierName: "Thai Steel Fasteners",
    stock: 20,
    unit: "แพ็ค",
    packSize: 100,
    unitPkg: "ตัว",
    itemType: "Consumable",
    category: "วัสดุสิ้นเปลือง",
  },
  {
    itemCode: "WASHER-M8-FLAT",
    itemName: "แหวนอีแปะ M8 (แพ็ค 200 ตัว)",
    supplierName: "Thai Steel Fasteners",
    stock: 30,
    unit: "แพ็ค",
    packSize: 200,
    unitPkg: "ตัว",
    itemType: "Consumable",
    category: "วัสดุสิ้นเปลือง",
  },
  {
    itemCode: "WASHER-M8-SPRING",
    itemName: "แหวนสปริง M8 (แพ็ค 200 ตัว)",
    supplierName: "Thai Steel Fasteners",
    stock: 30,
    unit: "แพ็ค",
    packSize: 200,
    unitPkg: "ตัว",
    itemType: "Consumable",
    category: "วัสดุสิ้นเปลือง",
  },
  {
    itemCode: "TAPE-ELEC-BLK-01",
    itemName: "เทปพันสายไฟ สีดำ 3M",
    supplierName: "3M Thailand",
    stock: 50,
    unit: "ม้วน",
    packSize: 1,
    unitPkg: "ม้วน",
    itemType: "Consumable",
    category: "วัสดุสิ้นเปลือง",
  },
  {
    itemCode: "TAPE-PIPE-01",
    itemName: "เทปพันเกลียวท่อ",
    supplierName: "SCG",
    stock: 40,
    unit: "ม้วน",
    packSize: 1,
    unitPkg: "ม้วน",
    itemType: "Consumable",
    category: "วัสดุสิ้นเปลือง",
  },
  {
    itemCode: "TAPE-MASKING-1IN",
    itemName: "เทปกระดาษกาว 1 นิ้ว",
    supplierName: "3M Thailand",
    stock: 30,
    unit: "ม้วน",
    packSize: 1,
    unitPkg: "ม้วน",
    itemType: "Consumable",
    category: "วัสดุสิ้นเปลือง",
  },
  {
    itemCode: "CUT-DISC-4IN",
    itemName: "ใบตัดเหล็ก 4 นิ้ว (กล่อง 50 ใบ)",
    supplierName: "Makita Thailand",
    stock: 10,
    unit: "กล่อง",
    packSize: 50,
    unitPkg: "ใบ",
    itemType: "Consumable",
    category: "วัสดุสิ้นเปลือง",
  },
  {
    itemCode: "GRIND-DISC-4IN",
    itemName: "ใบเจียรเหล็ก 4 นิ้ว (กล่อง 25 ใบ)",
    supplierName: "Makita Thailand",
    stock: 10,
    unit: "กล่อง",
    packSize: 25,
    unitPkg: "ใบ",
    itemType: "Consumable",
    category: "วัสดุสิ้นเปลือง",
  },
  {
    itemCode: "SANDPAPER-100",
    itemName: "กระดาษทรายขัดไม้ #100 (โหล)",
    supplierName: "3M Thailand",
    stock: 20,
    unit: "โหล",
    packSize: 12,
    unitPkg: "แผ่น",
    itemType: "Consumable",
    category: "วัสดุสิ้นเปลือง",
  },
  {
    itemCode: "SANDPAPER-320",
    itemName: "กระดาษทรายน้ำ #320 (โหล)",
    supplierName: "3M Thailand",
    stock: 20,
    unit: "โหล",
    packSize: 12,
    unitPkg: "แผ่น",
    itemType: "Consumable",
    category: "วัสดุสิ้นเปลือง",
  },
  {
    itemCode: "CABLETIE-6IN-WHT",
    itemName: "เคเบิ้ลไทร์ 6 นิ้ว สีขาว (ถุง 100 เส้น)",
    supplierName: "Local Supplier",
    stock: 50,
    unit: "ถุง",
    packSize: 100,
    unitPkg: "เส้น",
    itemType: "Consumable",
    category: "วัสดุสิ้นเปลือง",
  },

  // 2.2 อะไหล่เครื่องกล (Mechanical Parts)
  {
    itemCode: "BEARING-608",
    itemName: "ตลับลูกปืน 608-ZZ",
    supplierName: "NTN",
    stock: 100,
    unit: "ชิ้น",
    packSize: 1,
    unitPkg: "ชิ้น",
    itemType: "Consumable",
    category: "อะไหล่เครื่องกล",
  },
  {
    itemCode: "BEARING-6203",
    itemName: "ตลับลูกปืน 6203-2RS",
    supplierName: "SKF Thailand",
    stock: 120,
    unit: "ชิ้น",
    packSize: 1,
    unitPkg: "ชิ้น",
    itemType: "Consumable",
    category: "อะไหล่เครื่องกล",
  },
  {
    itemCode: "BEARING-6205",
    itemName: "ตลับลูกปืน 6205-2Z",
    supplierName: "SKF Thailand",
    stock: 150,
    unit: "ชิ้น",
    packSize: 1,
    unitPkg: "ชิ้น",
    itemType: "Consumable",
    category: "อะไหล่เครื่องกล",
  },
  {
    itemCode: "V-BELT-A50",
    itemName: "สายพาน V-Belt A50",
    supplierName: "Mitsuboshi Belting",
    stock: 30,
    unit: "เส้น",
    packSize: 1,
    unitPkg: "เส้น",
    itemType: "Consumable",
    category: "อะไหล่เครื่องกล",
  },
  {
    itemCode: "V-BELT-B50",
    itemName: "สายพาน V-Belt B50",
    supplierName: "Mitsuboshi Belting",
    stock: 80,
    unit: "เส้น",
    packSize: 1,
    unitPkg: "เส้น",
    itemType: "Consumable",
    category: "อะไหล่เครื่องกล",
  },
  {
    itemCode: "AIR-FILTER-01",
    itemName: "ไส้กรองอากาศ Compressor P-01",
    supplierName: "Atlas Copco",
    stock: 20,
    unit: "ชิ้น",
    packSize: 1,
    unitPkg: "ชิ้น",
    itemType: "Consumable",
    category: "อะไหล่เครื่องกล",
  },
  {
    itemCode: "OIL-SEAL-TC-30-52-7",
    itemName: "ซีลน้ำมัน TC 30x52x7",
    supplierName: "NOK",
    stock: 40,
    unit: "ชิ้น",
    packSize: 1,
    unitPkg: "ชิ้น",
    itemType: "Consumable",
    category: "อะไหล่เครื่องกล",
  },
  {
    itemCode: "ORING-SET-01",
    itemName: "ชุดโอริง (กล่อง)",
    supplierName: "NOK",
    stock: 10,
    unit: "กล่อง",
    packSize: 1,
    unitPkg: "กล่อง",
    itemType: "Consumable",
    category: "อะไหล่เครื่องกล",
  },

  // 2.3 เคมีภัณฑ์และของเหลว (Chemicals)
  {
    itemCode: "HYD-OIL-32",
    itemName: "น้ำมันไฮดรอลิก PTT H-32 (ถัง 200 ลิตร)",
    supplierName: "PTT Lubricants",
    stock: 3,
    unit: "ถัง",
    packSize: 200,
    unitPkg: "ลิตร",
    itemType: "Consumable",
    category: "เคมีภัณฑ์และของเหลว",
  },
  {
    itemCode: "HYD-OIL-68-20L",
    itemName: "น้ำมันไฮดรอลิก PTT H-68 (ถัง 20 ลิตร)",
    supplierName: "PTT Lubricants",
    stock: 10,
    unit: "ถัง",
    packSize: 20,
    unitPkg: "ลิตร",
    itemType: "Consumable",
    category: "เคมีภัณฑ์และของเหลว",
  },
  {
    itemCode: "GREASE-H1",
    itemName: "จาระบีทนความร้อน Food Grade (1 กก.)",
    supplierName: "SKF Thailand",
    stock: 20,
    unit: "กระป๋อง",
    packSize: 1,
    unitPkg: "กระป๋อง",
    itemType: "Consumable",
    category: "เคมีภัณฑ์และของเหลว",
  },
  {
    itemCode: "LOCTITE-243",
    itemName: "น้ำยากันคลาย Loctite 243",
    supplierName: "Henkel",
    stock: 15,
    unit: "ขวด",
    packSize: 1,
    unitPkg: "ขวด",
    itemType: "Consumable",
    category: "เคมีภัณฑ์และของเหลว",
  },
  {
    itemCode: "SILICONE-CLEAR-01",
    itemName: "ซิลิโคนใส GP",
    supplierName: "Dow",
    stock: 25,
    unit: "หลอด",
    packSize: 1,
    unitPkg: "หลอด",
    itemType: "Consumable",
    category: "เคมีภัณฑ์และของเหลว",
  },
  {
    itemCode: "SILICONE-RTV-RED",
    itemName: "ซิลิโคนแดง RTV (ทนความร้อน)",
    supplierName: "Dow",
    stock: 15,
    unit: "หลอด",
    packSize: 1,
    unitPkg: "หลอด",
    itemType: "Consumable",
    category: "เคมีภัณฑ์และของเหลว",
  },
  {
    itemCode: "SPRAY-RUST-01",
    itemName: "สเปรย์อเนกประสงค์ (WD-40)",
    supplierName: "WD-40",
    stock: 30,
    unit: "กระป๋อง",
    packSize: 1,
    unitPkg: "กระป๋อง",
    itemType: "Consumable",
    category: "เคมีภัณฑ์และของเหลว",
  },
  {
    itemCode: "SPRAY-CONTACT-01",
    itemName: "สเปรย์ล้างคอนแทค (Tronic)",
    supplierName: "Local Supplier",
    stock: 20,
    unit: "กระป๋อง",
    packSize: 1,
    unitPkg: "กระป๋อง",
    itemType: "Consumable",
    category: "เคมีภัณฑ์และของเหลว",
  },
  {
    itemCode: "THINNER-AAA",
    itemName: "ทินเนอร์ AAA (ปี๊บ)",
    supplierName: "Local Supplier",
    stock: 5,
    unit: "ปี๊บ",
    packSize: 1,
    unitPkg: "ปี๊บ",
    itemType: "Consumable",
    category: "เคมีภัณฑ์และของเหลว",
  },

  // 2.4 อุปกรณ์ความปลอดภัย (PPE)
  {
    itemCode: "SAFETY-GLOV",
    itemName: "ถุงมือหนังกันบาด (ขนาด L)",
    supplierName: "Safety Pro",
    stock: 10,
    unit: "โหล",
    packSize: 12,
    unitPkg: "คู่",
    itemType: "Consumable",
    category: "อุปกรณ์ความปลอดภัย (PPE)",
  },
  {
    itemCode: "GLOV-FABRIC-01",
    itemName: "ถุงมือผ้า 6 ขีด (แพ็ค 12 คู่)",
    supplierName: "Local Supplier",
    stock: 100,
    unit: "แพ็ค",
    packSize: 12,
    unitPkg: "คู่",
    itemType: "Consumable",
    category: "อุปกรณ์ความปลอดภัย (PPE)",
  },
  {
    itemCode: "EARPLUG-3M-01",
    itemName: "ที่อุดหู 3M (กล่อง 200 คู่)",
    supplierName: "3M Thailand",
    stock: 5,
    unit: "กล่อง",
    packSize: 200,
    unitPkg: "คู่",
    itemType: "Consumable",
    category: "อุปกรณ์ความปลอดภัย (PPE)",
  },
  {
    itemCode: "MASK-N95-01",
    itemName: "หน้ากาก N95 (กล่อง 20 ชิ้น)",
    supplierName: "3M Thailand",
    stock: 30,
    unit: "กล่อง",
    packSize: 20,
    unitPkg: "ชิ้น",
    itemType: "Consumable",
    category: "อุปกรณ์ความปลอดภัย (PPE)",
  },
  {
    itemCode: "GOGGLES-01",
    itemName: "แว่นตานิรภัย ใส",
    supplierName: "Safety Pro",
    stock: 40,
    unit: "อัน",
    packSize: 1,
    unitPkg: "อัน",
    itemType: "Consumable",
    category: "อุปกรณ์ความปลอดภัย (PPE)",
  },
  {
    itemCode: "HELMET-WHT-01",
    itemName: "หมวกนิรภัย สีขาว",
    supplierName: "Safety Pro",
    stock: 15,
    unit: "ใบ",
    packSize: 1,
    unitPkg: "ใบ",
    itemType: "Consumable",
    category: "อุปกรณ์ความปลอดภัย (PPE)",
  },
  {
    itemCode: "BOOT-9",
    itemName: "รองเท้านิรภัย (เบอร์ 9)",
    supplierName: "Safety Pro",
    stock: 10,
    unit: "คู่",
    packSize: 1,
    unitPkg: "คู่",
    itemType: "Consumable",
    category: "อุปกรณ์ความปลอดภัย (PPE)",
  },

  // 2.5 วัสดุไฟฟ้า (Electrical)
  {
    itemCode: "WIRE-THW-1.5",
    itemName: "สายไฟ THW 1.5 (เมตร)",
    supplierName: "Yazaki",
    stock: 1000,
    unit: "เมตร",
    packSize: 1,
    unitPkg: "เมตร",
    itemType: "Consumable",
    category: "วัสดุไฟฟ้า",
  },
  {
    itemCode: "WIRE-VCT-2.5",
    itemName: "สายไฟ VCT 2x2.5 (เมตร)",
    supplierName: "Yazaki",
    stock: 500,
    unit: "เมตร",
    packSize: 1,
    unitPkg: "เมตร",
    itemType: "Consumable",
    category: "วัสดุไฟฟ้า",
  },
  {
    itemCode: "LAMP-LED-T8-18W",
    itemName: "หลอดไฟ LED T8 18W",
    supplierName: "Philips",
    stock: 60,
    unit: "หลอด",
    packSize: 1,
    unitPkg: "หลอด",
    itemType: "Consumable",
    category: "วัสดุไฟฟ้า",
  },
  {
    itemCode: "FUSE-GLASS-5A",
    itemName: "ฟิวส์หลอดแก้ว 5A (กล่อง 100 ตัว)",
    supplierName: "Local Supplier",
    stock: 10,
    unit: "กล่อง",
    packSize: 100,
    unitPkg: "ตัว",
    itemType: "Consumable",
    category: "วัสดุไฟฟ้า",
  },
  {
    itemCode: "TERMINAL-RING-M4",
    itemName: "หางปลาหัวกลม M4 (ถุง 100 ตัว)",
    supplierName: "Local Supplier",
    stock: 20,
    unit: "ถุง",
    packSize: 100,
    unitPkg: "ตัว",
    itemType: "Consumable",
    category: "วัสดุไฟฟ้า",
  },
  {
    itemCode: "BREAKER-1P-10A",
    itemName: "เบรกเกอร์ 1P 10A",
    supplierName: "Panasonic",
    stock: 15,
    unit: "ตัว",
    packSize: 1,
    unitPkg: "ตัว",
    itemType: "Consumable",
    category: "วัสดุไฟฟ้า",
  },

  // 2.6 วัสดุทำความสะอาด (Cleaning)
  {
    itemCode: "BROOM-01",
    itemName: "ไม้กวาด",
    supplierName: "Local Supplier",
    stock: 10,
    unit: "ด้าม",
    packSize: 1,
    unitPkg: "ด้าม",
    itemType: "Consumable",
    category: "วัสดุทำความสะอาด",
  },
  {
    itemCode: "MOP-01",
    itemName: "ไม้ถูพื้น",
    supplierName: "Local Supplier",
    stock: 5,
    unit: "ด้าม",
    packSize: 1,
    unitPkg: "ด้าม",
    itemType: "Consumable",
    category: "วัสดุทำความสะอาด",
  },
  {
    itemCode: "CLEAN-FLOOR-5L",
    itemName: "น้ำยาถูพื้น 5 ลิตร",
    supplierName: "Local Supplier",
    stock: 8,
    unit: "แกลลอน",
    packSize: 1,
    unitPkg: "แกลลอน",
    itemType: "Consumable",
    category: "วัสดุทำความสะอาด",
  },
  {
    itemCode: "TRASHBAG-L",
    itemName: "ถุงขยะดำ ขนาด L (แพ็ค 1 กก.)",
    supplierName: "Local Supplier",
    stock: 30,
    unit: "แพ็ค",
    packSize: 1,
    unitPkg: "แพ็ค",
    itemType: "Consumable",
    category: "วัสดุทำความสะอาด",
  },
];

export function findStockInfo(stockData, itemCode) {
  return stockData.find((s) => s.itemCode === itemCode);
}

export const StatusBadge = ({ status }) => {
  switch (status) {
    case "อนุมัติ":
      return (
        <Badge className="bg-green-100 text-green-700 hover:bg-green-100">
          {status}
        </Badge>
      );
    case "รออนุมัติ":
      return (
        <Badge className="bg-orange-100 text-orange-700 hover:bg-orange-100">
          {status}
        </Badge>
      );
    case "ไม่อนุมัติ":
      return (
        <Badge className="bg-red-100 text-red-700 hover:bg-red-100">
          {status}
        </Badge>
      );
    case "ยกเลิก":
      return (
        <Badge className="bg-gray-100 text-gray-700 hover:bg-gray-100">
          {status}
        </Badge>
      );
    default:
      return <Badge variant="secondary">{status}</Badge>;
  }
};